### PR TITLE
Fixed failed to connect #612

### PR DESCRIPTION
**Pull request by TheDuffman85**
Fixed failed to connect #612 . Replaced requests with httpx in order to be able to use HTTP/2.

### CODE REVIEW

**Comment by AdrianGarside** [comment]
This is awesome work to find a solution so quickly. Please add back the comments you deleted and I'll complete the PR and run a new dev build.

**Comment by AdrianGarside** [comment]
Also a required validation is failing:
Error: R] [MANIFEST] Manifest keys are not sorted correctly: domain, name, then alphabetical order

requirements must be before ssdp

**Comment by TheDuffman85** [comment]
Sure no problem.

**Comment by TheDuffman85** [comment]
Done

**Comment by trevorstuart24** [comment]
i change the code as duffman suggested but when trying to add the integration again i get the error: Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by vordenken** [comment]
I installed the pre-release containing this fix but for me its not working:

```
Unable to install package httpx==0.27.2: ERROR: Cannot install httpx==0.27.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by ArikShemesh** [comment]
pre-release v2.0.23-dev3 worked for me without any issue.

**Comment by TheDuffman85** [comment]
@ArikShemesh  it was working fine with HA 2024.10 but failed with previous versions.

**Pull request merged**
