### PR TITLE
Make chamber image camera domain type

### LINKED ISSUE #365: P1P Chamber Camera Image Type
### Describe the feature

Is it possible to change the user setup so that the P1P camera sensor type can be selected as an image or camera? I want to bring the P1P chamber camera to Homekit, but it's impossible with image dishing.

### What device is this for?

P1P

### Other Information

_No response_

### PR DESCRIPTION
**Pull request by jawilson**
Makes the chamber "image" a `camera` domain type.

Fixes #365, #423, #531.

### CODE REVIEW

**Comment by EddyK69** [comment]
I'm using the v2.0.23-dev3 version and I only get a camera-feed when the printer is starting up a job. When it is actually printing, the feed is gone. I have a P1S

**Comment by steveneaston** [comment]
@AdrianGarside sorry to hijack this PR, but in the release notes for [2.0.23](https://github.com/greghesp/ha-bambulab/tree/v2.0.23) you mention:

> I found that in order to continue to show 'live' video in my dashboard inside a Picture-Elements, I had to apply a workaround to contain the camera image instead a custom layout card as picture-elements didn't natively support the camera card.

Both picture elements and picture card are working for me with live video with the new camera entity:

```yaml
type: picture-entity
entity: camera.p1s_camera
camera_image: camera.p1s_camera
camera_view: live
show_state: false
show_name: false
```

```yaml
type: picture-elements
elements: []
camera_image: camera.p1s_camera
camera_view: live
```

With `picture-elements`, I found that if you add any elements, you need to use `camera_view: auto`. But for my use case, `picture-entity` is preferrable anyway.

**Comment by AdrianGarside** [comment]
@steveneaston thanks I will give that a go.

**Comment by AdrianGarside** [comment]
This is what I currently have. If I replace that custom:layout-card with anything else the camera doesn't render.
```
type: custom:tabbed-card
options: {}
tabs:
  - card:
      type: vertical-stack
      cards:
        - type: picture-elements
          elements:
            - type: custom:layout-card
              layout_type: masonry
              cards:
                - type: picture-entity
                  entity: camera.p1p_XXX_camera
                  show_state: false
                  show_name: false
                  camera_view: live
              style:
                left: 50%
                top: 50%
                width: 104%
                height: 107%
        ....
```
Ah, I was trying to insert the camera as a card within the elements list, but I see you can just have the camera as a background for the entire picture-elements at the top level:
```
type: custom:tabbed-card
options: {}
tabs:
  - card:
      type: vertical-stack
      cards:
        - type: picture-elements
          camera_image: camera.XXX_camera
          camera_view: auto
          elements:
      ...
```
More compact, doesn't have the weird sizing problems I had with custom:layout-card so much better.

**Comment by kaandorp** [comment]
After the update the camera image doesn't render at all. Not on a dashboard, but also not directly on the device page. 

The link to the image is https://[domain]/api/camera_proxy_stream/camera.bambu_labs_a1_camera?token=b319ff977dddd5bc34927da7c7adfdsfe17dfc3f1df59f8505bd9fd5e633bfea047e2f9c803a4

If tried restarting HA and the printer. Other sensors seem to be working with the exception of the camera.

**Comment by AdrianGarside** [comment]
Anything in the debug logs?

**Comment by kaandorp** [comment]
> Anything in the debug logs? What version of home assistant? Does downgrading to the version where it's an image work again?

I have to admit that after clearing the Safari cache it seems to work again :)

**Comment by kaandorp** [comment]
> > Anything in the debug logs? What version of home assistant? Does downgrading to the version where it's an image work again?
> 
> I have to admit that after clearing the Safari cache it seems to work again :)

Whoops. A bit too fast. It seems to be working in the native app on macOS and on my iPhone. It also seems to work on Chrome. It just doesn't work very well on Safari. If you clear the cache it works again. If you keep the image open you suddenly see the entire page reloading and the image is broken. There is nothing in the debug log. HA is the latest version. I can try some earlier versions, but I'm actually doubting if these problems were not in Safari before.

**Comment by AdrianGarside** [comment]
Since it's a standard HA camera entity at this point, there's likely nothing I can do to fix Safari mishandling rendering it :(

**Comment by kaandorp** [comment]
> Since it's a standard HA camera entity at this point, there's likely nothing I can do to fix Safari mishandling rendering it :(

It seems to be a known issue for quite some time: 
https://github.com/home-assistant/core/issues/13995

So nothing we can do about it I’m afraid.

**Comment by AdrianGarside** [comment]
Please open an issue for this - I'll likely add in a configuration to have the older image 'fake' camera sensor active instead. I'm not sure how quickly I'll be able to get to it though - work got crazy again.

**Pull request merged**
