### PR TITLE
Added remaining filament amount to AMS trays.

### PR DESCRIPTION
**Pull request by myMartek**
To solve the open issue #249 I created a pull request which implements the reading of the filament. My solution is quite simple: I simply added the remain parameter as it is. For filaments that are not Bambulabs or when the reading is disabled in the printers settings the value will simply be -1 and otherwise represent a percentage from 0 - 100%

### CODE REVIEW

**Comment by myMartek** [comment]
I added a pull request which simply adds the remain value as it is to each AMS Slot. It can be -1 if there is no bambu filament or when the option to track the state is disabled but for me it is still a valid reading we can show as it is.

Bildschirmfoto 2023-11-24 um 22 28 08

**Comment by myMartek** [comment]
I also added the tag_uid parameter for identifying the filament spool.

**Comment by AdrianGarside** [comment]
main is our release branch - can you change this PR to be against develop instead please.

**Comment by myMartek** [comment]
Sure!

**Comment by AdrianGarside** [comment]
https://github.com/greghesp/ha-bambulab/releases/tag/v1.9.2-dev1

**Pull request merged**
