### PR TITLE
Bambu Cloud China MQTT Connection Modified

### PR DESCRIPTION
**Pull request by iluna8**
Modify the Bambu Cloud MQTT address "us.mqtt.bambulab.com" hardcoding.

For China, set to "cn.mqtt.bambulab.com" and other global..."us.mqtt.bambulab.com".

### CODE REVIEW

**Comment by AdrianGarside** [comment]
Sorry, most of these changes are incorrect with the recent updates. Thank you for bringing the incorrect mqtt host address to my attention - I will make the fixes instead since it can be done more cleanly than this.

**Comment by AdrianGarside** [comment]
Also you should not be targeting your PRs against main - that is the release branch. Please target PRs to develop in the future.

**Comment by AdrianGarside** [comment]
Please review: https://github.com/greghesp/ha-bambulab/pull/344

**Comment by AdrianGarside** [comment]
And please test:
https://github.com/greghesp/ha-bambulab/releases/tag/v2.0.3-dev3

**Comment by iluna8** [comment]
I'd like to get some advice on Bambu local rock. Can you reach me at luna88quie@gmail.com ?

**Pull request closed without merging**
