### PR TITLE
Correct greek localization filename

### PR DESCRIPTION
**Pull request by AdrianGarside**
The filename was incorrect.

### CODE REVIEW

**Review by Chreece — COMMENTED** [review]
After the update the entity names on UI returned to English

**Comment by AdrianGarside** [comment]
Fixed with #690

**Comment by Chreece** [comment]
Unfortunately, that didn't help. The entities remain in English.

**Comment by AdrianGarside** [comment]
This is weird - I tested it before i made that fix but I too am now not seeing the entities in greek when I re-test.

**Comment by AdrianGarside** [comment]
The sensor values are being localized successfully into Greek. But the entity names remain in English but that's true with all languages that have localization support in the integration. I suspect they might fix if you delete/re-add the printer but since printer addition is currently broken due to cloudflare I can't test that theory.

**Comment by Chreece** [comment]
Just checked, the entity values are also not translated, I will investigate it further

**Comment by Chreece** [comment]
Yes the .json file should be named el.json, after that the entities and entity names are in greek.
May I ask why did you want to rename it from start?

**Comment by AdrianGarside** [comment]
That's not working for me: 
image

But at this point I can delete the file and the sensor values remain localized so I'm not sure what to think.

**Comment by Chreece** [comment]
image

After renaming to el.json what's your UI language?

image

**Comment by Chreece** [comment]
I'm using greek all the time in my UI and the only possibility for the translation to work is the `el.json`, so maybe the problem is when someone swaps languages.
Did you just change the language or also the country?

**Comment by Chreece** [comment]
*a reminder, if you change the language the entity states get translated automatically from the UI, it's a core function. 
The translations on the custom_integrations translate also the entities, so maybe you changed the language and you saw the greek state translations and not the friendly names that are shown in UI

**Comment by AdrianGarside** [comment]
Well, there's no need for the more specific language tag in this case so we can rename the file to el.json given you're shown it does work then. HA probably doesn't have support for the more specific versions like el-gr except in cases where there isn't a generic one that works (i.e. zh)

**Pull request merged**
